excluded:
- Carthage
- Pods

disabled_rules:
- line_length
- force_cast
- todo
- trailing_whitespace
- closure_parameter_position
- trailing_comma
- opening_brace
- colon
- identifier_name
- cyclomatic_complexity
- function_body_length

identifier_name:
  min_length:
    warning: 1

type_name:
  max_length: 50

identifier_name:
  allowed_symbols: "_"